### ISSUE TITLE
How many data are needed to train a new model?

### ISSUE THREAD

**Issue by JinChengneng** [pcko1/Deep-Drug-Coder#6]
Hi there, thanks for your efforts to ```Deep Drug Coder```. Your paper and blogs are all informative.

I want to train a new model for a specific target, however, the number of active molecules is limited. I wonder how many molecules are needed to train a new model. Moreover, if the molecules are not enough, can we use technology like transfer learning to this problem?

**Comment by pcko1** [comment]
Hi Jin, thanks for your comment. I would like to underline that issues on the repo should reflect programming ones rather than scientific discussion. For scientific discussion, please utilize the comments section of the [blog post](https://www.cheminformania.com/master-your-molecule-generator-2-direct-steering-of-conditional-recurrent-neural-networks-crnns/).

In order to train a QSAR model, you typically need datasets of 100-1000s of molecules from my short experience in the domain. Kindly refer to existing literature for more accurate numbers. The number of active molecules in your dataset is relevant to the quality of the QSAR model and not the cRNN. To this end, if your trained QSAR model performs adequately on a left-out set, then it should be suitable to be used to label the molecules for the training set of the cRNN. As of now, we haven't tried training the cRNN in a transfer learning fashion, i.e. train the same cRNN model on two different datasets using the same descriptors.
