### ISSUE TITLE
Error when retrain the model.

### ISSUE THREAD

**Issue by hcji** [pcko1/Deep-Drug-Coder#7]
Hi, there, 
Nice work!  I want to retrain (fine-tune, I gauss) with my data, but I got an error, Here is my code:

    mols =  [Chem.MolFromSmiles(s) for s in List_of_Smiles]
    model_name = "pretrain/heteroencoder_model"     
    model = ddc.DDC(x = mols, y = mols, model_name = model_name)      
    model.fit(epochs = 50, lr = 0.0001, mini_epochs = 3, patience = 3, model_name = 'model/fine_tune')

Error Information:

    File "<ipython-input-1-b4f1980edca8>", line 25, in <module>
      model.fit(epochs = 50, lr = 0.0001, mini_epochs = 3, patience = 3, model_name = 'model/fine_tune')

    File "C:\Users\jihon\Anaconda3\lib\site-packages\ddc_pub-0.3-py3.7.egg\ddc_pub\ddc_v3.py", line 1016, in fit
      verbose=verbose,

    File "C:\Users\jihon\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training.py", line 1297, in fit_generator
      steps_name='steps_per_epoch')

    File "C:\Users\jihon\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py", line 144, in model_iteration
      shuffle=shuffle)

    File "C:\Users\jihon\Anaconda3\lib\site-packages\tensorflow_core\python\keras\engine\training_generator.py", line 477, in convert_to_generator_like
      num_samples = int(nest.flatten(data)[0].shape[0])

    AttributeError: 'HetSmilesGenerator' object has no attribute 'shape'

My tensorflow version is 2.0.0
Thank you,

**Comment by pcko1** [comment]
Hi @hcji , thanks for reaching out! This error is due to some backwards incompatibility of the newer versions of tensorflow with the older ones that we used to develop our code. This is resolved in the branch `nightly`.

Kindly run `git checkout nightly` to switch branch and then follow the instructions found here](https://github.com/pcko1/Deep-Drug-Coder/blob/nightly/demo_heteroencoder_train.ipynb).

**Comment by hcji** [comment]
> Hi @hcji , thanks for reaching out! This error is due to some backwards incompatibility of the newer versions of tensorflow with the older ones that we used to develop our code. This is resolved in the branch `nightly`.
> 
> Kindly run `git checkout nightly` to switch branch and then follow the instructions found [here](https://github.com/pcko1/Deep-Drug-Coder/blob/nightly/demo_heteroencoder_train.ipynb).

Fixed. Thank you very much.

**Comment by hcji** [comment]
@pcko1 Now, I can load the model, but when I load and retrain the heteroencoder_model with my own data, I get an OOM error, Can I reduce the batch_size of the trained heteroencoder_model or some somehow to fix this？ My GPU is GTX 2080Ti. Thank you.

**Comment by pcko1** [comment]
You could try with a smaller batch size. Otherwise, I will need to refactor the generators to enable training with larger datasets. This is something that I've had in mind for some time but haven't had the time to implement. As of now, I am not sure there is much you can do without re-writing the way data is loaded to the model.
